In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [4]:
c = np.dot(a,b)

In [5]:
print(c)

250007.6275158108


In [6]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])


In [7]:
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [8]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [9]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [18]:
a = np.random.randn(5) #DONT USE RANK 1 ARRAY
print(a)


[-0.74493814 -0.17062676 -0.27458511  0.31739262 -0.78513836]


In [11]:
print(a.shape)

(5,)


In [12]:
#TRANSPOSE
print(a.T)

[ 0.41340655 -0.98031264  0.13611662  1.25845665  1.13032886]


In [13]:
print(np.dot(a,a.T))

4.011802078367916


In [14]:
a = np.random.randn(5,1)
print(a)

[[ 0.61278164]
 [-0.06782667]
 [ 0.51642467]
 [-2.08975916]
 [ 0.55805687]]


In [16]:
print(a.T)
#TWO SQUARE BRACKETS

[[ 0.61278164 -0.06782667  0.51642467 -2.08975916  0.55805687]]


In [17]:
print(np.dot(a,a.T))

[[ 0.37550134 -0.04156294  0.31645556 -1.28056605  0.34196701]
 [-0.04156294  0.00460046 -0.03502736  0.1417414  -0.03785114]
 [ 0.31645556 -0.03502736  0.26669444 -1.07920319  0.28819434]
 [-1.28056605  0.1417414  -1.07920319  4.36709333 -1.16620446]
 [ 0.34196701 -0.03785114  0.28819434 -1.16620446  0.31142747]]


In [19]:
#SIGMOID FUCTION

def sigmoid(x):

    s = 1/(1 + np.exp(-x))

    return s

In [25]:
sigmoid(3)

np.float64(0.9525741268224334)

In [28]:
x = np.array([1,2,3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [29]:
print(x+3)

[4 5 6]


In [30]:
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [31]:
#SIGMOID GRADIENT

def sigmoid_dervative(x):

    s = sigmoid(x)
    ds = s * (1 - s)

    return ds

In [32]:
x = np.array([1,2,3])
print('sigmoid_dervative:', sigmoid_dervative(x))

sigmoid_dervative: [0.19661193 0.10499359 0.04517666]


In [33]:
#softmax

def softmax(x):
    x_exp = np.exp(x)
    total = np.sum(x_exp,axis=1,keepdims=True)
    x = x_exp/total

    return x

In [37]:
x = np.array([[9,2,5,0,0],
            [7,5,0,0,0]])
print("softmax:\n", softmax(x))

softmax:
 [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [ ]:
#L1 LOSS FUNCTION:   
#     loss = np.sum(abs(y-yhat))

def L1(yhat,y):
    diff = yhat - y
    x = np.abs(diff)
    l1 = np.sum(x)

    return l1

In [ ]:
#L2 LOSS FUNCTION:
#   loss = np.dot(y-yhat,y-yhat)

def L2(yhat,y):
    diff = yhat - y
    diff_2 = diff**2
    l2 = np.sum(diff_2)

    return l2

In [41]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print('L1 :',(L1(yhat,y)))
print('L2 :',(L2(yhat,y)))


L1 : 1.1
L2 : 0.43
